config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'metadata', to: 'home#metadata'
  get 'links', to: 'home#links'

  resources :posts, path: '/marketplace'
  get 'posts/remove/:id', to: 'posts#destroy', as: 'post_remove'
  get 'posts/remove_photos/:id', to: 'posts#remove_photos', as: 'post_remove_photos'

  resources :cars
  get 'cars/remove/:id', to: 'cars#destroy', as: 'car_remove'

  resources :rooms
  resources :egg_orders, only: %i[edit update]

  get 'transfers/new', to: 'transfers#new', as: 'send_money'
  post 'transfers', to: 'transfers#create'

  get 'setup/routing', to: 'setup#routing'
  get 'setup/welcome', to: 'setup#welcome'
  get 'setup/app', to: 'setup#app'
  post 'setup/save_app', to: 'setup#save_app'
  get 'setup/allowlist', to: 'setup#allowlist'
  post 'setup/save_allowlist', to: 'setup#save_allowlist'
  get 'setup/admin', to: 'setup#admin'
  get 'setup/done', to: 'setup#done'
  post 'setup/save_done', to: 'setup#save_done'

  resources :funds
  get 'bank_statements', to: 'funds#statements'
  get 'funds/remove/:id', to: 'funds#destroy', as: 'fund_remove'
  get 'funds/close/:id', to: 'funds#close', as: 'fund_close'

  resources :meals
  get 'meals/:id/sign-up', to: 'meal_payments#new', as: 'meal_sign_up'
  post 'meals/:id/create-sign-up', to: 'meal_payments#create', as: 'create_meal_sign_up'
  get 'meals/:id/sign-up/:payment_id', to: 'meal_payments#edit', as: 'edit_meal_sign_up'
  post 'meals/:id/update-sign-up/:payment_id', to: 'meal_payments#update', as: 'update_meal_sign_up'
  get 'meals/:id/cancel-sign-up/:payment_id', to: 'meal_payments#destroy', as: 'cancel_meal_sign_up'
  get 'meals/:id/close', to: 'meals#close', as: 'close_meal'
  post 'meals/:id/confirm_close', to: 'meals#confirm_close', as: 'confirm_close_meal'
  get 'fetch_meals', to: 'meals#fetch_meals'
  get 'fetch_meal_attendees', to: 'meals#fetch_meal_attendees'

  namespace :bookings do
    resources :guests
    get 'guests/cancel/:id', to: 'guests#destroy', as: 'cancel_room_booking'
    get 'guests/confirm_booking/:id', to: 'guests#confirm_booking', as: 'confirm_room_booking'
    get 'fetch_bookings', to: 'guests#fetch_bookings'
    get 'prepare_new_room_booking', to: 'guests#prepare_new_room_booking'

    resources :cars
    get 'cars/cancel/:id', to: 'cars#destroy', as: 'cancel_car_booking'
    get 'fetch_car_bookings', to: 'cars#fetch_car_bookings'
    get 'prepare_new_car_booking', to: 'cars#prepare_new_car_booking'

    resources :areas
    get 'areas/cancel/:id', to: 'areas#destroy', as: 'cancel_area_booking'
    get 'fetch_area_bookings', to: 'areas#fetch_area_bookings'
    get 'prepare_new_area_booking', to: 'areas#prepare_new_area_booking'
  end

  namespace :admin do
    get 'guest_rooms'
    get 'mark_balance_as_paid'
    get 'mark_booking_as_confirmed'
    get 'money'
    get 'egg_orders'
    get 'car_booking_payments'
    get 'meals'
    get 'meals/:id', to: '/admin#meal', as: 'meal'
    get 'close_meal'
    get 'download_meals', defaults: { format: :csv }
    get 'area_bookings'
    get 'mark_egg_payment_as_paid'
    get 'mark_car_booking_payment_as_paid'
    get 'notify_about_egg_delivery'
    get 'mark_area_booking_as_confirmed'
    post 'add_money_to_fund'
  end

  get 'take_egg_order', to: 'egg_payments#take_order'

  get 'settings', to: 'user_settings#edit', as: 'user_settings'
  post 'save_user_settings', to: 'user_settings#save_user_settings'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/views/admin/_egg_order_summary.html.haml
- total_number_of_boxes = order.egg_payments.sum(&:number_of_boxes)
- paid_payments = order.egg_payments.paid.select('user_id, state, sum(number_of_boxes) as total_number_of_boxes').group(:user_id, :state)
- pending_payments = order.egg_payments.pending.select('user_id, state, number_of_boxes as total_number_of_boxes, id')
- payments = paid_payments + pending_payments

.delivery-section
  %h5
    = "#{order.delivery_date_label} delivery"
    - if order.purchase_date >= @current_archive_threshold && payments.present?
      = link_to '"Eggs are here!" email', admin_notify_about_egg_delivery_path({ id: order.id }), class: 'btn btn-primary btn-sm ', type: 'button'

  .number-boxes
    = "Total boxes available: #{order.max_boxes.present? ? order.max_boxes : 'no limit'}"
    - if Date.current < order.purchase_date
      = link_to 'Update number', edit_egg_order_path(order), class: 'btn btn-primary btn-sm update-num-btn', type: 'button'

  - if payments.empty?
    = 'No purchase for this order.'
  - else
    %table.table.table-striped
      %thead
        %tr
          %th{scope: 'col'} Name
          %th{scope: 'col'} Num. boxes
          %th{scope: 'col'} Amount
          %th{scope: 'col'} Status
      %tbody
        - payments.each do |payment|
          %tr
            %td= payment.user.full_name
            %td= payment.total_number_of_boxes
            %td= number_to_currency(order.price * payment.total_number_of_boxes)
            %td
              = payment.state.capitalize
              - if payment.pending?
                .mark-as-paid
                  = link_to 'Mark as paid', admin_mark_egg_payment_as_paid_path({ id: payment.id }), class: 'btn btn-primary btn-sm', type: 'button'
      %tfoot
        %tr
          %td= 'TOTAL'
          %td= total_number_of_boxes
          %td= number_to_currency(order.price * total_number_of_boxes)
          %td= ''

app/views/admin/area_bookings.html.haml
.container.lg
  %section.user-page.event-lists
    %h3
      = 'Coordinate CH area bookings'

    %hr

    .sub-section
      %h5
        = "Bookings to review"
      - if @unconfirmed_bookings.present?
        - @unconfirmed_bookings.each do |booking|
          - user = booking.user
          - contact = [email_html_link_for(user.email), phone_number_html_link_for(user.phone_number)].compact.join(' - ')
          .event
            .event-summary
              = link_to booking.summary, bookings_area_path(booking), class: 'link'
            .details= "Booked on #{booking.booking_datetime} by #{user.full_name} (#{contact})".html_safe
            .details
              = link_to 'Confirm booking', admin_mark_area_booking_as_confirmed_path({ id: booking.id }), class: 'btn btn-primary btn-sm', type: 'button'
              = link_to 'Delete booking', bookings_cancel_area_booking_path(booking), onclick: "return confirm('Are you sure you want to delete this booking?');", class: 'btn btn-danger btn-sm', type: 'button'
      - else
        %p= 'No area booking with a pending confirmation to review for now.'

app/views/admin/car_booking_payments.html.haml
.container.lg
  %section.user-page.event-lists.admin-screen
    %h3
      = 'Pending car booking payments'

    %hr

    .sub-section
      - if @pending_payments.none?
        .event
          There is no pending car booking payments.
      - else
        %table.table.table-striped
          %thead
            %tr
              %th{scope: 'col'} Booking period
              %th{scope: 'col'} Member name
              %th{scope: 'col'} Cost
              %th{scope: 'col'} 
          %tbody
            - @pending_payments.each do |payment|
              %tr
                %td= "#{payment.period_start} - #{payment.period_end}"
                %td= payment.user.full_name
                %td= "#{number_to_currency(payment.amount)}"
                %td
                  .mark-as-paid
                    = link_to 'Mark as paid', admin_mark_car_booking_payment_as_paid_path({ id: payment.id }), class: 'btn btn-primary btn-sm', type: 'button'

app/views/admin/egg_orders.html.haml
.container.lg
  %section.user-page.event-lists.admin-screen
    %h3
      = 'Manage egg orders'
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#EggEmailsModal'}
        %span.question-mark ✉️

    %hr

    .sub-section
      - if EggOrder.none?
        .event
          No egg order has been made (yet).
      - else
        - if @revenue_for_three_last_months.present?
          %h5 Recent total revenue summary

          %ul
            - @revenue_for_three_last_months.each do |date, days_and_costs|
              %li= "For #{date} - #{days_and_costs.map{|day, cost| "#{day.capitalize}: #{number_to_currency(cost)}"}.join('; ')}"

          %hr

        - @next_egg_orders.each do |order|
          = render 'egg_order_summary', order: order

        %hr

        #accordionEggOrders.accordion.accordion-flush
          .accordion-item
            %h2#pastEggOrders.accordion-header
              %button.accordion-button.collapsed{"aria-controls" => "eggOrderCollapse", "aria-expanded" => "false", "data-bs-target" => "#eggOrderCollapse", "data-bs-toggle" => "collapse", type: "button"}
                = 'Recent past egg orders'
            #eggOrderCollapse.accordion-collapse.collapse{"aria-labelledby" => "pastEggOrders", "data-bs-parent" => "#accordionFlushExample"}
              .accordion-body
                - @past_egg_orders.each do |order|
                  = render 'egg_order_summary', order: order

= render 'admin/modals/view_egg_emails'

app/views/admin/guest_rooms.html.haml
.container.lg
  %section.user-page.event-lists
    %h3
      = 'Coordinate guest rooms'

    %hr

    .sub-section
      %h4
        = "Unconfirmed bookings to review"
      - if @unconfirmed_bookings.present?
        - @unconfirmed_bookings.each do |booking|
          - user = booking.user
          - contact = [email_html_link_for(user.email), phone_number_html_link_for(user.phone_number)].compact.join(' - ')
          .event
            .event-summary
              = link_to booking.summary, bookings_guest_path(booking), class: 'link'
            .details= "Booked from #{booking.start_date.to_date} to #{booking.end_date.to_date}, by #{user.full_name} (#{contact})".html_safe
            .details= "Asked for confirmation by email #{days_since_confirmation_email_for(booking)} #{'day'.pluralize(days_since_confirmation_email_for(booking))} ago"
            .details
              = link_to 'Confirm', admin_mark_booking_as_confirmed_path({ id: booking.id }), class: 'btn btn-primary btn-sm', type: 'button'
              = link_to 'Cancel', bookings_cancel_room_booking_path(booking), onclick: "return confirm('Are you sure you want to cancel this booking?');", class: 'btn btn-danger btn-sm', type: 'button'
      - else
        %p= 'There is no booking with a pending confirmation to review.'

    .sub-section
      %h4
        = "Pending payments"
      - if @bookings_with_payments.present?
        - @bookings_with_payments.each do |booking|
          - user = booking.user
          - payment = booking.room_payment
          - contact = [email_html_link_for(user.email), phone_number_html_link_for(user.phone_number)].compact.join(' - ')
          .event
            .event-summary
              = link_to booking.summary, bookings_guest_path(booking), class: 'link'
            .details= "- Booked from #{booking.start_date.to_date} to #{booking.end_date.to_date}, by #{user.full_name} (#{contact})".html_safe
            .details= "- #{payment.description}: #{number_to_currency(payment.amount)}"
            .details
              = link_to 'Mark booking as paid', admin_mark_balance_as_paid_path({ id: booking.id }), class: 'balance-paid btn btn-primary btn-sm', type: 'button'
      - else
        %p= 'There is no booking with a pending payment.'

app/views/admin/meal.html.haml
- meal_payments = @meal.meal_payments.includes(meal_seating_choices: [:meal_portion_choices, :meal_seating_attendees])
- payment_total = meal_payments.sum(&:amount)
- meal_cost = @meal.cost
- meal_user = @meal.user
- common_meal_transfer = payment_total - meal_cost if meal_cost.present?
- common_meal_balance = Fund.common_meals.balance
- meal_fund_name = Fund.common_meals.name

.container.lg
  %section.user-page.event-lists.admin-screen
    %h4
      = "#{meal_date_for(@meal)} - #{@meal.title}"

    %hr

    %p= "Meal prepared by #{meal_user.full_name}. See #{link_to 'meal details', meal_path(@meal)}.".html_safe

    .sub-section
      %h5= 'Attendees'

      - if meal_payments.none?
        %p= 'No payment (paid or pending) associated to this meal yet.'
      - else
        %table.table.table-striped
          %thead
            %tr
              %th{scope: 'col'} Name(s)
              %th{scope: 'col'} Portion(s)
              %th{scope: 'col'} Amount
          %tbody
            - meal_payments.each do |payment|
              - attendees = payment.meal_seating_choices.map(&:attendee_labels).flatten.join(', ')
              %tr
                %td= attendees
                %td= cost_breakdown_for(payment)
                %td= number_to_currency(payment.amount)
            %tfoot
              %tr
                %td= 'Meal revenue'
                %td= ''
                %td= number_to_currency(payment_total)

    .sub-section
      %h5= 'Balance'
      %p= "#{meal_fund_name} fund balance: #{number_to_currency(common_meal_balance)}"
      %table.table.table-striped
        %tbody
          %tr
            %td= 'Meal Revenue'
            %td= number_to_currency(payment_total)
            %td= ''
          %tr
            %td= 'Meal Cost'
            - if meal_cost.nil?
              %td= "Please #{link_to 'update the meal cost', edit_meal_path(@meal)} first".html_safe
            - elsif !@meal.closed?
              %td= "#{number_to_currency(meal_cost)} #{link_to 'Update', edit_meal_path(@meal)}".html_safe
            - else
              %td= number_to_currency(meal_cost)
            %td= ''
        %tfoot
          %tr
            %td= 'Common meal fund gain/loss'
            - if meal_cost.nil?
              %td= 'N/A'
            - else
              %td= number_to_currency(common_meal_transfer)
            %td= ''

    - unless meal_cost.nil?
      - if @meal.closed?
        %p= "The common meal fund has already been debitted accordingly. This meal is closed."
      - elsif meal_cost > common_meal_balance
        %p= "⚠️ You cannot close this meal, as there is not enough money in the #{meal_fund_name} fund to debit! Please add more money in that fund first."
      - else
        %p= "By clicking on \"Debit fund\", you will take out #{number_to_currency(meal_cost)} from this fund. #{meal_admin_action_call(meal_user)}" 

        .text-center.text-lg-start.mt-4.pt-2
          = link_to "Debit fund", admin_close_meal_path({id: @meal.id}), class: 'btn btn-primary btn-md'

app/views/admin/meals.html.haml
.container.lg
  %section.user-page.event-lists.admin-screen
    %h3
      = @is_showing_closed_list ? 'Closed meals' : 'Meals to close'
      %span.links
        = link_to '📄', admin_download_meals_path, title: 'Download closed meal data', class: 'action-post'

    %hr

    .sub-section
      - if @is_showing_closed_list
        = link_to 'Show list of meals to close', admin_meals_path
      - else
        = link_to 'Show list of closed meals', admin_meals_path({closed: 1})

    .sub-section
      - @recent_meals.each do |meal|
        .event
          .event-summary
            = link_to "#{meal_date_for(meal)} - #{meal.title}", admin_meal_path(meal.id)

app/views/admin/money.html.haml
.container.lg
  %section.user-page
    %h3= 'Add money to a fund'

    %hr

    = form_with url: admin_add_money_to_fund_path do |f|
      .row
        .col-12.col-md-6
          .form-outline.mb-4
            = f.label :amount, 'Amount to add', class: 'form-label required'
            = f.number_field :amount, min: 0.01, step: 0.01, class: 'form-control form-control-md'

      .row
        .col-12.col-md-6
          .form-outline.mb-4
            = f.label :interac, 'Interac ref. #', class: 'form-label'
            = f.text_field :interac, class: 'form-control form-control-md'

      .row
        .col-12.col-md-6
          .form-outline.mb-4
            = f.label :recipient_description, 'Note', class: 'form-label'
            = f.text_field :recipient_description, class: 'form-control form-control-md'

      .row
        .col-12.col-md-6
          .form-outline.mb-4
            = f.label :fund_id, 'Recipient (Community fund or member)', class: 'form-label required'
            = f.select :fund_id, options_from_collection_for_select(Fund.active.community.order(:name), :id, :community_display_name, nil) + options_from_collection_for_select(Fund.active.personal.order(:name), :id, :name, nil), {}, { class: 'form-select search-form-field' }

      .text-center.text-lg-start.mt-4.pt-2
        = link_to "Cancel", root_path, class: 'btn btn-secondary'
        = f.submit "Add money", class: 'btn btn-primary btn-md submit-btn', data: { confirm: "Are you sure you want to add this amount to this fund?" }

    %hr

    %h5= 'Latest 10 operations'

    %table.table.table-striped
      %thead
        %tr
          %th{scope: 'col'} Date and time
          %th{scope: 'col'} Recipient (member or fund)
          %th{scope: 'col'} Interac ref. #
          %th{scope: 'col'} Amount
      %tbody
        - Transfer.without_sender.last(10).reverse.each do |transfer|
          %tr
            %td= transfer.created_at.strftime('%b %d %Y, %l.%M%P')
            %td= transfer.recipient.name
            %td= transfer.masked_interac
            %td= number_to_currency(transfer.amount)