config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'metadata', to: 'home#metadata'
  get 'links', to: 'home#links'

  resources :posts, path: '/marketplace'
  get 'posts/remove/:id', to: 'posts#destroy', as: 'post_remove'
  get 'posts/remove_photos/:id', to: 'posts#remove_photos', as: 'post_remove_photos'

  resources :cars
  get 'cars/remove/:id', to: 'cars#destroy', as: 'car_remove'

  resources :rooms
  resources :egg_orders, only: %i[edit update]

  get 'transfers/new', to: 'transfers#new', as: 'send_money'
  post 'transfers', to: 'transfers#create'

  get 'setup/routing', to: 'setup#routing'
  get 'setup/welcome', to: 'setup#welcome'
  get 'setup/app', to: 'setup#app'
  post 'setup/save_app', to: 'setup#save_app'
  get 'setup/allowlist', to: 'setup#allowlist'
  post 'setup/save_allowlist', to: 'setup#save_allowlist'
  get 'setup/admin', to: 'setup#admin'
  get 'setup/done', to: 'setup#done'
  post 'setup/save_done', to: 'setup#save_done'

  resources :funds
  get 'bank_statements', to: 'funds#statements'
  get 'funds/remove/:id', to: 'funds#destroy', as: 'fund_remove'
  get 'funds/close/:id', to: 'funds#close', as: 'fund_close'

  resources :meals
  get 'meals/:id/sign-up', to: 'meal_payments#new', as: 'meal_sign_up'
  post 'meals/:id/create-sign-up', to: 'meal_payments#create', as: 'create_meal_sign_up'
  get 'meals/:id/sign-up/:payment_id', to: 'meal_payments#edit', as: 'edit_meal_sign_up'
  post 'meals/:id/update-sign-up/:payment_id', to: 'meal_payments#update', as: 'update_meal_sign_up'
  get 'meals/:id/cancel-sign-up/:payment_id', to: 'meal_payments#destroy', as: 'cancel_meal_sign_up'
  get 'meals/:id/close', to: 'meals#close', as: 'close_meal'
  post 'meals/:id/confirm_close', to: 'meals#confirm_close', as: 'confirm_close_meal'
  get 'fetch_meals', to: 'meals#fetch_meals'
  get 'fetch_meal_attendees', to: 'meals#fetch_meal_attendees'

  namespace :bookings do
    resources :guests
    get 'guests/cancel/:id', to: 'guests#destroy', as: 'cancel_room_booking'
    get 'guests/confirm_booking/:id', to: 'guests#confirm_booking', as: 'confirm_room_booking'
    get 'fetch_bookings', to: 'guests#fetch_bookings'
    get 'prepare_new_room_booking', to: 'guests#prepare_new_room_booking'

    resources :cars
    get 'cars/cancel/:id', to: 'cars#destroy', as: 'cancel_car_booking'
    get 'fetch_car_bookings', to: 'cars#fetch_car_bookings'
    get 'prepare_new_car_booking', to: 'cars#prepare_new_car_booking'

    resources :areas
    get 'areas/cancel/:id', to: 'areas#destroy', as: 'cancel_area_booking'
    get 'fetch_area_bookings', to: 'areas#fetch_area_bookings'
    get 'prepare_new_area_booking', to: 'areas#prepare_new_area_booking'
  end

  namespace :admin do
    get 'guest_rooms'
    get 'mark_balance_as_paid'
    get 'mark_booking_as_confirmed'
    get 'money'
    get 'egg_orders'
    get 'car_booking_payments'
    get 'meals'
    get 'meals/:id', to: '/admin#meal', as: 'meal'
    get 'close_meal'
    get 'download_meals', defaults: { format: :csv }
    get 'area_bookings'
    get 'mark_egg_payment_as_paid'
    get 'mark_car_booking_payment_as_paid'
    get 'notify_about_egg_delivery'
    get 'mark_area_booking_as_confirmed'
    post 'add_money_to_fund'
  end

  get 'take_egg_order', to: 'egg_payments#take_order'

  get 'settings', to: 'user_settings#edit', as: 'user_settings'
  post 'save_user_settings', to: 'user_settings#save_user_settings'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/views/shared/_alerts.html.haml
- role_for_alert = alert == I18n.t('devise.failure.unauthenticated') ? 'info' : 'danger'

- if notice
  = alert_for(role: 'success', text: notice)

- if alert
  = alert_for(role: role_for_alert, text: alert)

- if flash[:error]
  = alert_for(role: 'danger', text: flash[:error])

- if flash[:info]
  = alert_for(role: 'info', text: flash[:info])

- if flash[:success]
  = alert_for(role: 'success', text: flash[:success])

app/views/shared/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container.my-3
    .container.lg
      .row
        .col-12.col-md-6.link-group
          %h5 This website
          %ul.list-unstyled.text-small
            %li
              = link_to 'Source code', 'https://codeberg.org/etienne/treehouse', class: 'link', target: '_blank'
            %li
              = link_to 'Issue tracker', 'https://codeberg.org/etienne/treehouse/issues', class: 'link', target: '_blank'

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-green
  .container
    - if @maintenance_is_on
      = link_to "#{Setting.app_name} in maintenance", root_path, id: 'maintenanceOn', class: 'navbar-brand'
    - else
      = link_to Setting.app_name, root_path, class: 'navbar-brand'

    - if user_signed_in? && Setting.setup_done?
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          - if current_user.admin? && !current_user.emeritus?
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                Admin
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                - if current_user.guest_room_coordinator?
                  %li
                    = link_to 'See all rooms', rooms_path, {class: 'dropdown-item'}
                  %li
                    = link_to 'Coordinate guest rooms', admin_guest_rooms_path, {class: 'dropdown-item'}
                - if current_user.area_booking_coordinator?
                  %li
                    = link_to 'Coordinate CH area bookings', admin_area_bookings_path, {class: 'dropdown-item'}

                - if current_user.car_booking_payment_admin?
                  %li
                    = link_to 'Pending car booking payments', admin_car_booking_payments_path, {class: 'dropdown-item'}

                - if current_user.common_meal_admin?
                  %li
                    = link_to 'Manage meals', admin_meals_path, {class: 'dropdown-item'}

                - if current_user.fund_admin?
                  %li
                    = link_to 'Add money to a fund', admin_money_path, {class: 'dropdown-item'}

                - if current_user.egg_admin?
                  %li
                    = link_to 'Manage egg orders', admin_egg_orders_path, {class: 'dropdown-item'}


          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Services
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to 'Send money', send_money_path, {class: 'dropdown-item'}
              %li
                = link_to 'Meals', meals_path, {class: 'dropdown-item'}

              - if !current_user.emeritus?
                %li
                  = link_to 'Book a car', bookings_cars_path, {class: 'dropdown-item'}

                %li
                  = link_to 'Book a CH area', bookings_areas_path, {class: 'dropdown-item'}

                %li
                  = link_to 'Book a guest room', bookings_guests_path, {class: 'dropdown-item'}

              %li
                = link_to 'Marketplace', posts_path, {class: 'dropdown-item'}

          - unless current_user.emeritus?
            %li.nav-item
              = link_to 'Links', links_path, { class: 'nav-link' }

          - if @maintenance_is_on
            %li.nav-item
              %span
                %a#maintenanceOn.nav-link.disabled{'aria-disabled' => 'true'}
                  = "Maintenance is on!"

        %form.right-menu.d-flex
          %ul.navbar-nav.me-auto.mb-2.mb-lg-0
            %li.nav-item
              = link_to "💵 #{number_to_currency(current_user.fund.balance)}".html_safe, funds_path, { class: 'nav-link' }

            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.first_name
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                %li
                  %span.dropdown-item.email
                    = current_user.email
                %li
                  = link_to 'Edit my profile', edit_user_registration_path, { class: 'dropdown-item' }
                %li
                  = link_to 'My settings', user_settings_path, { class: 'dropdown-item' }
                %li
                  %hr.dropdown-divider
                %li
                  = link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: 'dropdown-item'