config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'metadata', to: 'home#metadata'
  get 'links', to: 'home#links'

  resources :posts, path: '/marketplace'
  get 'posts/remove/:id', to: 'posts#destroy', as: 'post_remove'
  get 'posts/remove_photos/:id', to: 'posts#remove_photos', as: 'post_remove_photos'

  resources :cars
  get 'cars/remove/:id', to: 'cars#destroy', as: 'car_remove'

  resources :rooms
  resources :egg_orders, only: %i[edit update]

  get 'transfers/new', to: 'transfers#new', as: 'send_money'
  post 'transfers', to: 'transfers#create'

  get 'setup/routing', to: 'setup#routing'
  get 'setup/welcome', to: 'setup#welcome'
  get 'setup/app', to: 'setup#app'
  post 'setup/save_app', to: 'setup#save_app'
  get 'setup/allowlist', to: 'setup#allowlist'
  post 'setup/save_allowlist', to: 'setup#save_allowlist'
  get 'setup/admin', to: 'setup#admin'
  get 'setup/done', to: 'setup#done'
  post 'setup/save_done', to: 'setup#save_done'

  resources :funds
  get 'bank_statements', to: 'funds#statements'
  get 'funds/remove/:id', to: 'funds#destroy', as: 'fund_remove'
  get 'funds/close/:id', to: 'funds#close', as: 'fund_close'

  resources :meals
  get 'meals/:id/sign-up', to: 'meal_payments#new', as: 'meal_sign_up'
  post 'meals/:id/create-sign-up', to: 'meal_payments#create', as: 'create_meal_sign_up'
  get 'meals/:id/sign-up/:payment_id', to: 'meal_payments#edit', as: 'edit_meal_sign_up'
  post 'meals/:id/update-sign-up/:payment_id', to: 'meal_payments#update', as: 'update_meal_sign_up'
  get 'meals/:id/cancel-sign-up/:payment_id', to: 'meal_payments#destroy', as: 'cancel_meal_sign_up'
  get 'meals/:id/close', to: 'meals#close', as: 'close_meal'
  post 'meals/:id/confirm_close', to: 'meals#confirm_close', as: 'confirm_close_meal'
  get 'fetch_meals', to: 'meals#fetch_meals'
  get 'fetch_meal_attendees', to: 'meals#fetch_meal_attendees'

  namespace :bookings do
    resources :guests
    get 'guests/cancel/:id', to: 'guests#destroy', as: 'cancel_room_booking'
    get 'guests/confirm_booking/:id', to: 'guests#confirm_booking', as: 'confirm_room_booking'
    get 'fetch_bookings', to: 'guests#fetch_bookings'
    get 'prepare_new_room_booking', to: 'guests#prepare_new_room_booking'

    resources :cars
    get 'cars/cancel/:id', to: 'cars#destroy', as: 'cancel_car_booking'
    get 'fetch_car_bookings', to: 'cars#fetch_car_bookings'
    get 'prepare_new_car_booking', to: 'cars#prepare_new_car_booking'

    resources :areas
    get 'areas/cancel/:id', to: 'areas#destroy', as: 'cancel_area_booking'
    get 'fetch_area_bookings', to: 'areas#fetch_area_bookings'
    get 'prepare_new_area_booking', to: 'areas#prepare_new_area_booking'
  end

  namespace :admin do
    get 'guest_rooms'
    get 'mark_balance_as_paid'
    get 'mark_booking_as_confirmed'
    get 'money'
    get 'egg_orders'
    get 'car_booking_payments'
    get 'meals'
    get 'meals/:id', to: '/admin#meal', as: 'meal'
    get 'close_meal'
    get 'download_meals', defaults: { format: :csv }
    get 'area_bookings'
    get 'mark_egg_payment_as_paid'
    get 'mark_car_booking_payment_as_paid'
    get 'notify_about_egg_delivery'
    get 'mark_area_booking_as_confirmed'
    post 'add_money_to_fund'
  end

  get 'take_egg_order', to: 'egg_payments#take_order'

  get 'settings', to: 'user_settings#edit', as: 'user_settings'
  post 'save_user_settings', to: 'user_settings#save_user_settings'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:metadata]

  NUMBER_OF_RESULTS_PER_PAGE = 10

  def index
    page_number = params[:page] || 1

    @household = current_user.household
    @upcoming_room_bookings = current_user.room_bookings.includes(:room).upcoming
    @upcoming_area_bookings = current_user.area_bookings.includes(:room).upcoming
    @upcoming_car_bookings = current_user.car_bookings.includes(:car).upcoming
    @pending_car_booking_payments = current_user.car_booking_payments.pending
    @upcoming_meals = current_user.upcoming_meals
    @posts = current_user.posts.page(page_number).per(NUMBER_OF_RESULTS_PER_PAGE)
    @egg_payments = current_user.egg_payments.upcoming_deliveries
  end

  def links; end

  def metadata
    render json: { revision: short_sha }
  end

  private

  def short_sha
    if Rails.env.production?
      File.read(Rails.root.join('REVISION')).strip.freeze[0..6]
    else
      `git rev-parse --short HEAD | tr -d '\n'`
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.haml
- no_event = [@upcoming_room_bookings, @upcoming_car_bookings, @upcoming_area_bookings, @upcoming_meals, @posts, @egg_payments].all?(&:empty?)

.container.lg
  %section.user-page.event-lists
    %h3
      = 'Home page'
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#homeHelpModal'}
        %span.question-mark ?

    %hr

    - if no_event
      .sub-section
        Nothing is happening! (no new notification)

    - if @upcoming_car_bookings.present? || @pending_car_booking_payments.present?
      .sub-section
        %h4
          = "🚗 Your car bookings"
        - if @pending_car_booking_payments.present?
          .card.border-warning.mb-3.col-12.col-md-6
            .card-body
              %p.card-text You need to pay for the following car bookings:
              %ul
                - @pending_car_booking_payments.each do |payment|
                  %li= "From #{payment.period_start} to #{payment.period_end}: #{number_to_currency(payment.amount)}"
              %p.car-text Please send an etransfer to Wayne. Thanks!

        - if @upcoming_car_bookings.present?
          - @upcoming_car_bookings.each do |booking|
            .event
              .event-summary
                = link_to "Booked '#{booking.car.title}'", bookings_car_path(booking), class: 'link'
              .details= booking.booking_datetime

    - if @egg_payments.present?
      .sub-section
        %h4
          = "🥚 Your upcoming egg deliveries"
        - @egg_payments.each do |egg_payment|
          .event
            %span.details
              = "Delivery on #{egg_payment.egg_order.purchase_date.strftime('%a %B %d').strip} (#{egg_payment.number_of_boxes} dozen) "
            - if egg_payment.paid?
              %span.badge.bg-success= "Paid"
            - else
              %span.badge.bg-warning.text-dark= "Payment pending"


    - if @upcoming_meals.present?
      .sub-section
        %h4
          = "🍴 Your next meals"
        - @upcoming_meals.each do |meal|
          .event
            .event-summary
              = link_to meal.title, meal_path(meal), class: 'link'
            .details= meal_reg_date_and_time_for(meal, @household)

    - if @upcoming_area_bookings.present?
      .sub-section
        %h4
          = "🏠 Your CH area bookings"
        - @upcoming_area_bookings.each do |booking|
          .event
            .event-summary
              = link_to booking.room.name, bookings_area_path(booking), class: 'link'
            .details= booking.booking_datetime

    - if @upcoming_room_bookings.present?
      .sub-section
        %h4
          = "🛌 Your guest room bookings"
        - @upcoming_room_bookings.each do |booking|
          .event
            .event-summary
              = link_to booking.summary, bookings_guest_path(booking), class: 'link'
            .details= "from #{booking.start_date.to_date} to #{booking.end_date.to_date}"
            - if booking.payment_required?
              - payment = booking.room_payment
              .details
                %span.badge.bg-warning.text-dark= "Payment required: #{number_to_currency(payment.amount)}"

    - if @posts.present?
      .sub-section#postList
        %h4
          = "📄 Your posts"
        - @posts.each do |post|
          .event
            .event-summary
              = link_to post.title, post_path(post), class: 'link'
            .details= price_option_label_for(post)

        = paginate @posts

= render 'home/modals/home_help'

app/views/home/links.html.haml
.container.lg
  %section.user-page.useful-links
    %h3= "Links to #{Setting.app_name} resources"

    %hr

    .sub-section
      .description
        (All links open a Google document or another website in a new tab)

      .row
        %ul.list-unstyled
          %li
            = link_to 'Everything you need to know about Coming Home', Rails.application.credentials.dig(:tve_resources, :everything), target: '_blank'
          %li
            = link_to 'Learning Tree', Rails.application.credentials.dig(:tve_resources, :learning_tree), target: '_blank'
          %li
            = link_to 'Members Calendar', Rails.application.credentials.dig(:tve_resources, :calendar), target: '_blank'
          %li
            = link_to 'Members List', Rails.application.credentials.dig(:tve_resources, :members), target: '_blank'
          %li
            = link_to 'Policy Directory', Rails.application.credentials.dig(:tve_resources, :policy_logbook), target: '_blank'
          %li
            = link_to 'Template Directory', Rails.application.credentials.dig(:tve_resources, :template_directory), target: '_blank'