config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'metadata', to: 'home#metadata'
  get 'links', to: 'home#links'

  resources :posts, path: '/marketplace'
  get 'posts/remove/:id', to: 'posts#destroy', as: 'post_remove'
  get 'posts/remove_photos/:id', to: 'posts#remove_photos', as: 'post_remove_photos'

  resources :cars
  get 'cars/remove/:id', to: 'cars#destroy', as: 'car_remove'

  resources :rooms
  resources :egg_orders, only: %i[edit update]

  get 'transfers/new', to: 'transfers#new', as: 'send_money'
  post 'transfers', to: 'transfers#create'

  get 'setup/routing', to: 'setup#routing'
  get 'setup/welcome', to: 'setup#welcome'
  get 'setup/app', to: 'setup#app'
  post 'setup/save_app', to: 'setup#save_app'
  get 'setup/allowlist', to: 'setup#allowlist'
  post 'setup/save_allowlist', to: 'setup#save_allowlist'
  get 'setup/admin', to: 'setup#admin'
  get 'setup/done', to: 'setup#done'
  post 'setup/save_done', to: 'setup#save_done'

  resources :funds
  get 'bank_statements', to: 'funds#statements'
  get 'funds/remove/:id', to: 'funds#destroy', as: 'fund_remove'
  get 'funds/close/:id', to: 'funds#close', as: 'fund_close'

  resources :meals
  get 'meals/:id/sign-up', to: 'meal_payments#new', as: 'meal_sign_up'
  post 'meals/:id/create-sign-up', to: 'meal_payments#create', as: 'create_meal_sign_up'
  get 'meals/:id/sign-up/:payment_id', to: 'meal_payments#edit', as: 'edit_meal_sign_up'
  post 'meals/:id/update-sign-up/:payment_id', to: 'meal_payments#update', as: 'update_meal_sign_up'
  get 'meals/:id/cancel-sign-up/:payment_id', to: 'meal_payments#destroy', as: 'cancel_meal_sign_up'
  get 'meals/:id/close', to: 'meals#close', as: 'close_meal'
  post 'meals/:id/confirm_close', to: 'meals#confirm_close', as: 'confirm_close_meal'
  get 'fetch_meals', to: 'meals#fetch_meals'
  get 'fetch_meal_attendees', to: 'meals#fetch_meal_attendees'

  namespace :bookings do
    resources :guests
    get 'guests/cancel/:id', to: 'guests#destroy', as: 'cancel_room_booking'
    get 'guests/confirm_booking/:id', to: 'guests#confirm_booking', as: 'confirm_room_booking'
    get 'fetch_bookings', to: 'guests#fetch_bookings'
    get 'prepare_new_room_booking', to: 'guests#prepare_new_room_booking'

    resources :cars
    get 'cars/cancel/:id', to: 'cars#destroy', as: 'cancel_car_booking'
    get 'fetch_car_bookings', to: 'cars#fetch_car_bookings'
    get 'prepare_new_car_booking', to: 'cars#prepare_new_car_booking'

    resources :areas
    get 'areas/cancel/:id', to: 'areas#destroy', as: 'cancel_area_booking'
    get 'fetch_area_bookings', to: 'areas#fetch_area_bookings'
    get 'prepare_new_area_booking', to: 'areas#prepare_new_area_booking'
  end

  namespace :admin do
    get 'guest_rooms'
    get 'mark_balance_as_paid'
    get 'mark_booking_as_confirmed'
    get 'money'
    get 'egg_orders'
    get 'car_booking_payments'
    get 'meals'
    get 'meals/:id', to: '/admin#meal', as: 'meal'
    get 'close_meal'
    get 'download_meals', defaults: { format: :csv }
    get 'area_bookings'
    get 'mark_egg_payment_as_paid'
    get 'mark_car_booking_payment_as_paid'
    get 'notify_about_egg_delivery'
    get 'mark_area_booking_as_confirmed'
    post 'add_money_to_fund'
  end

  get 'take_egg_order', to: 'egg_payments#take_order'

  get 'settings', to: 'user_settings#edit', as: 'user_settings'
  post 'save_user_settings', to: 'user_settings#save_user_settings'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/controllers/bookings/areas_controller.rb
# frozen_string_literal: true

module Bookings
  class AreasController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_current_tve_member
    before_action :area_booking, only: %i[show edit update destroy]

    def index
      @areas = Room.ch_areas
    end

    def new
      @area_booking = AreaBooking.new(
        start_time: params[:start_time],
        end_time: params[:end_time]
      )
    end

    def create
      booking = AreaBooking.new(area_booking_params)
      service = AreaBookings::CreateService.new(booking, user: current_user)

      @area_booking = service.execute

      if @area_booking.valid?
        set_confirmation_message

        redirect_to bookings_areas_path
      else
        render 'new'
      end
    end

    def update
      if @area_booking.update(area_booking_params)
        redirect_to bookings_areas_path, notice: 'Your booking was updated successfully.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def fetch_area_bookings
      dates = formatted_start_and_end_dates

      render json: { bookings: bookings_for(dates[:start], dates[:end]) }
    end

    def prepare_new_area_booking
      booking_data = VerifyAreaBookingService.new(
        start_time: params[:start_time],
        end_time: params[:end_time]
      ).execute

      render json: { booking: booking_data }
    end

    def destroy
      booking_user_id = area_booking.user_id

      if area_booking.destroy
        if current_user.id == booking_user_id
          flash[:success] = 'Your CH area booking has now been cancelled.'
          redirect_to bookings_areas_path
        end
      else
        flash[:error] = 'This booking could not be cancelled.'
        redirect_to bookings_areas_path
      end
    end

    private

    def area_booking
      @area_booking ||= AreaBooking.find(params[:id])
    end

    def bookings_for(start_date, end_date)
      return [] unless start_date && end_date

      start_time = DateTime.parse(start_date.to_s).beginning_of_day
      end_time = DateTime.parse(end_date.to_s).end_of_day

      AreaBooking.includes(:user)
                 .where('(end_time BETWEEN ? AND ?) OR (start_time BETWEEN ? AND ?)',
                        start_time, end_time, start_time, end_time)
                 .map do |b|
                   b.serialize_for_calendar_for(current_user)
                 end.flatten
    end

    def formatted_start_and_end_dates
      start_calendar_date = params[:start_date]
      end_calendar_date = params[:end_date]
      return { start: nil, end: nil } unless start_calendar_date && end_calendar_date

      begin
        { start: Date.parse(start_calendar_date), end: Date.parse(end_calendar_date) }
      rescue ArgumentError
        { start: nil, end: nil }
      end
    end

    def area_booking_params
      area_params = params.require(:area_booking).permit(:start_time, :end_time, :room_id, :name, :description, :level)

      area_params['level'] = area_params['level'].to_i

      area_params
    end

    def set_confirmation_message
      if @area_booking.pending?
        flash[:info] = 'Your reservation has been saved but it requires approval from the CoHo circle. Please contact them.'
      else
        flash[:success] = 'Your CH area booking has been saved.'
      end
    end
  end
end

app/controllers/bookings/cars_controller.rb
# frozen_string_literal: true

module Bookings
  class CarsController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_current_tve_member
    before_action :car_booking, only: %i[show edit update destroy]
    before_action :ensure_host, only: %i[edit destroy]
    before_action :past_booking, only: %i[edit update destroy]

    def index
      @cars = Car.all
    end

    def new
      @car_booking = CarBooking.new(
        start_time: params[:start_time],
        end_time: params[:end_time],
        expected_distance: 10
      )
    end

    def create
      @car_booking = CarBooking.new(car_booking_params)
      @car_booking.user = current_user

      if @car_booking.save
        flash[:success] = 'Your car booking has been saved.'

        redirect_to bookings_cars_path
      else
        render 'new'
      end
    end

    def update
      if @car_booking.update(car_booking_params)
        redirect_to bookings_cars_path, notice: 'Your car booking was updated successfully.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      booking_user_id = car_booking.user_id

      if !car_booking.past_or_in_progress_booking? && car_booking.destroy
        if current_user.id == booking_user_id
          flash[:success] = 'Your car booking has now been cancelled.'
          redirect_to bookings_cars_path
        end
      else
        flash[:error] = 'This booking could not be cancelled.'
        redirect_to bookings_cars_path
      end
    end

    def fetch_car_bookings
      dates = formatted_start_and_end_dates

      render json: { bookings: bookings_for(dates[:start], dates[:end]) }
    end

    def prepare_new_car_booking
      booking_data = VerifyCarBookingService.new(
        start_time: params[:start_time],
        end_time: params[:end_time]
      ).execute

      render json: { booking: booking_data }
    end

    private

    def bookings_for(start_date, end_date)
      return [] unless start_date && end_date

      start_time = DateTime.parse(start_date.to_s).beginning_of_day
      end_time = DateTime.parse(end_date.to_s).end_of_day

      CarBooking.includes(:user)
                .where('(end_time BETWEEN ? AND ?) OR (start_time BETWEEN ? AND ?)',
                       start_time, end_time, start_time, end_time)
                .map do |b|
                  b.serialize_for_calendar_for(current_user)
                end.flatten
    end

    def formatted_start_and_end_dates
      start_calendar_date = params[:start_date]
      end_calendar_date = params[:end_date]
      return { start: nil, end: nil } unless start_calendar_date && end_calendar_date

      begin
        { start: Date.parse(start_calendar_date), end: Date.parse(end_calendar_date) }
      rescue ArgumentError
        { start: nil, end: nil }
      end
    end

    def car_booking_params
      params.require(:car_booking).permit(:start_time, :end_time, :car_id, :note, :expected_distance)
    end

    def car_booking
      @car_booking ||= CarBooking.find(params[:id])
    end

    def ensure_host
      return if current_user.id == @car_booking.user_id

      flash[:error] = 'You cannot edit or delete this booking.'
      redirect_to bookings_car_path(@car_booking)
    end

    def past_booking
      return unless @car_booking.past_booking?

      flash[:error] = 'You cannot update or cancel a past car booking'
      redirect_to bookings_car_path(@car_booking)
    end
  end
end

app/controllers/bookings/guests_controller.rb
# frozen_string_literal: true

module Bookings
  class GuestsController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_current_tve_member
    before_action :room_booking, only: %i[show edit update destroy confirm_booking]
    before_action :ensure_host, only: %i[edit destroy confirm_booking]

    def index
      @guest_rooms = Room.for_guests
      @this_month_bookings = bookings_for(
        Date.current.beginning_of_month,
        Date.current.end_of_month
      ).to_json
    end

    def new
      @room_booking = RoomBooking.new(
        start_date: params[:start_date],
        end_date: params[:end_date]
      )
    end

    def create
      booking = RoomBooking.new(room_booking_params)
      service = RoomBookings::CreateService.new(booking, user: current_user)

      @room_booking = service.execute

      if @room_booking.valid?
        flash[:success] = @room_booking.success_message
        redirect_to bookings_guests_path
      else
        render 'new'
      end
    end

    def update
      if @room_booking.update(room_booking_params)
        redirect_to bookings_guests_path, notice: 'Your guest room booking was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      start_date = room_booking.start_date.to_date
      end_date = room_booking.end_date.to_date
      booking_user_id = room_booking.user_id

      if room_booking.destroy
        if current_user.id == booking_user_id
          flash[:success] = "Your booking from #{start_date} to #{end_date} has now been cancelled."
          redirect_to bookings_guests_path
        elsif current_user.guest_room_coordinator?
          flash[:success] = "The booking from #{start_date} to #{end_date} has now been cancelled."
          redirect_to admin_guest_rooms_path
        end

      else
        flash[:error] = 'This booking could not be cancelled.'
        redirect_to bookings_guests_path
      end
    end

    def confirm_booking
      @room_booking.confirmed!

      redirect_to bookings_guests_path, notice: 'Your guest room booking is now confirmed.'
    end

    def fetch_bookings
      dates = formatted_start_and_end_dates

      render json: { bookings: bookings_for(dates[:start], dates[:end]) }
    end

    def prepare_new_room_booking
      booking_data = VerifyRoomBookingService.new(
        start_date: params[:start_date],
        end_date: params[:end_date]
      ).execute

      render json: { booking: booking_data }
    end

    private

    def bookings_for(start_date, end_date)
      return [] unless start_date && end_date

      RoomBooking.includes(user: :household)
                 .where('(end_date BETWEEN ? AND ?) OR (start_date BETWEEN ? AND ?)',
                        start_date, end_date, start_date, end_date)
                 .map do |b|
                   b.serialize_for_calendar_for(current_user)
                 end
    end

    def formatted_start_and_end_dates
      start_calendar_date = params[:start_date]
      end_calendar_date = params[:end_date]
      return { start: nil, end: nil } unless start_calendar_date && end_calendar_date

      begin
        { start: Date.parse(start_calendar_date), end: Date.parse(end_calendar_date) }
      rescue ArgumentError
        { start: nil, end: nil }
      end
    end

    def room_booking
      @room_booking ||= RoomBooking.find(params[:id])
    end

    def ensure_host
      return if current_user.id == @room_booking.user_id
      return if current_user.guest_room_coordinator?

      flash[:error] = 'You cannot edit or delete this booking.'
      redirect_to bookings_guest_path(@room_booking)
    end

    def room_booking_params
      params.require(:room_booking).permit(:start_date, :end_date, :room_id, :description)
    end
  end
end

app/helpers/bookings/area_helper.rb
# frozen_string_literal: true

module Bookings
  module AreaHelper
    def options_for_area_booking_level
      green = AreaBooking.green_level
      yellow = AreaBooking.yellow_level
      red = AreaBooking.red_level

      [
        [[green.color, green.label].join(' '), green.id],
        [[yellow.color, yellow.label].join(' '), yellow.id],
        [[red.color, red.label].join(' '), red.id]
      ]
    end
  end
end

app/helpers/bookings/cars_helper.rb
# frozen_string_literal: true

module Bookings
  module CarsHelper
    def car
      @car ||= Car.find_by(id: params[:car_id]) || @car_booking.car
    end

    def electric_car_note
      "When you come back from your trip to #{Setting.app_name}, please plug in this car to recharge it if the battery level is low"
    end

    def non_electric_car_note
      "Remember to get some gasoline on your way back to #{Setting.app_name}, bring it back with the gas level you found the car with."
    end
  end
end

app/helpers/bookings/guests_helper.rb
# frozen_string_literal: true

module Bookings
  module GuestsHelper
    def guest_room
      @guest_room ||= Room.find_by(id: params[:room_id]) || @room_booking.room
    end

    def area_room
      @area_room ||= Room.find_by(id: params[:room_id]) || @area_booking.room
    end

    def booking_credit_left_for(booked_nights, year)
      number_of_booked_nights = booked_nights[year] || 0
      max_num_nights = RoomBooking::MAX_NUMBER_OF_FREE_NIGHTS
      nights_left = max_num_nights - number_of_booked_nights

      if nights_left.positive?
        "#{year}: #{nights_left} free #{'night'.pluralize(nights_left)} left"
      else
        "#{year}: $#{RoomBooking::PRICE_PER_NIGHT} per night"
      end
    end

    def days_since_confirmation_email_for(booking)
      return 0 unless booking
      return 0 if booking.confirmed_at

      confirmation_date = (booking.start_date - RoomBooking::CONFIRMATION_BEFORE_START_MONTHS.months).to_date

      [(Date.current - confirmation_date).to_i, 0].max
    end

    def label_for_purpose(purpose)
      {
        Room::GUEST => 'Guest room',
        Room::CH_AREA => 'Common House area'
      }[purpose]
    end
  end
end

app/views/bookings/guests/_form.html.haml
= form_for @room_booking, url: path_for_room_booking do |f|
  - if @room_booking.errors.any?
    .alert.alert-danger{ role: 'alert' }
      = "Please fix #{pluralize(@room_booking.errors.count, "error")} before saving this guest room booking:"
      %ul
        - @room_booking.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :room_id, { value: guest_room.id }

  .row
    .col-12.col-md-6
      .form-outline.mb-4
        = f.label :start_date, 'Start date', class: 'form-label required'
        = f.date_field :start_date, class: 'form-control form-control-lg'

  .row
    .col-12.col-md-6
      .form-outline.mb-4
        = f.label :end_date, 'End date', class: 'form-label required'
        = f.date_field :end_date, class: 'form-control form-control-lg'

  .row
    .col-12.col-md-9
      .form-outline.mb-4
        = f.label :description, 'Notes', class: 'form-label'
        = f.text_area :description, class: 'form-control', rows: 8, placeholder: 'Please write anything you think the community should know about this guest room booking.'

  .row
    .text-center.text-lg-start.mt-4.pt-2
      = link_to "Cancel", bookings_guests_path, class: 'btn btn-secondary'
      = f.submit "#{@room_booking.persisted? ? 'Update' : 'Create'} this booking", class: 'btn btn-primary btn-md submit-btn'

app/views/bookings/guests/edit.html.haml
.container.lg
  %section.user-page.new-object
    %h3
      = "Edit booking at #{guest_room.name}"
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#newBookingHelp'}
        %span.question-mark ?

    %hr
      = render 'form', path_for_room_booking: bookings_guest_path(@room_booking)

= render 'bookings/modals/new_and_edit_help'

app/views/bookings/guests/index.html.haml
- content_for :head do
  = javascript_import_module_tag 'fullcalendar.min'
  = javascript_import_module_tag 'guest'

.container.lg
  %section.user-page.booking-page#guest-booking{ data: { bookings: @this_month_bookings } }
    %h3
      = 'Book a guest room'
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#guestBookingHelpModal'}
        %span.question-mark ?

    %hr

    .booking-credit
      - number_of_booked_nights = current_user.num_booked_nights
      - today = Date.current
      %span.household-title
        = current_user.household_mention
      %span
        %br
        = booking_credit_left_for(number_of_booked_nights, today.year)
        %br
        = booking_credit_left_for(number_of_booked_nights, today.next_year.year)

    - @guest_rooms.each do |room|
      .bookable-legend
        .square-color{ style: "background-color: #{room.calendar_color}"}
        %span.name
          = room.name
        %span
          = "- #{room.description}"
    .bookable-legend
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#guestBookingHelpModal'}
        %span More details and options about these rooms...

    #scrollToPoint
    .alert.alert-danger#roomErrorMessage{ role: 'alert', style: 'display: none;' }
    #roomBookingForm{ style: 'display: none;' }
      %hr
      %h5 Your new booking
      = form_with url: new_bookings_guest_url, method: :get do |form|
        = form.hidden_field :start_date
        = form.hidden_field :end_date
        .row
          .col-12.col-md-4.room-summary-text
            %span#newRoomBookingSummary
          .col-12.col-md-4
            = form.select :room_id, content_tag(:option, 'Which room are you booking?', value: '') + options_from_collection_for_select(Room.for_guests, :id, :name, nil), {}, { class: 'form-select search-form-field' }
          .col-12.col-md-3
            = form.submit 'Confirm booking', class: 'btn btn-primary submit-btn', id: 'confirmRoomBooking', name: nil

    #calendar
      .spinner-border.text-success{role: 'status'}
        %span.visually-hidden Loading...

= render 'bookings/modals/guest_help'
= render 'bookings/modals/view_guest_booking'

app/views/bookings/guests/new.html.haml
.container.lg
  %section.user-page.new-object
    %h3
      = "New booking (\"#{guest_room.name}\")"
      %a{href: '#', 'data-bs-toggle': 'modal', 'data-bs-target': '#newBookingHelp'}
        %span.question-mark ?

    %hr
      = render 'form', path_for_room_booking: bookings_guests_path

= render 'bookings/modals/new_and_edit_help'

app/views/bookings/guests/show.html.haml
- poster = @room_booking.user

.container.lg
  %section.user-page#showBooking
    %h3
      = @room_booking.summary
      - if @room_booking.show_edit_link_for?(current_user)
        %span.links
          = link_to '✏️', edit_bookings_guest_path(@room_booking), class: 'action-booking'
          = link_to '🗑️', bookings_cancel_room_booking_path(@room_booking), onclick: "return confirm('Are you sure you want to delete this booking?');", class: 'action-booking bin'

    %hr

    - if @room_booking.payment_required? && @room_booking.user_id == current_user.id
      - payment = @room_booking.room_payment
      .row
        .col-12
          .alert.alert-warning{role: 'alert'}
            = "You need to pay #{number_to_currency(payment.amount)} to confirm this booking. Please talk to the guest room coordinator."

    .row
      .col-12
        %span= 'Start date:'
        = @room_booking.start_date.to_date

    .row
      .col-12
        %span= 'End date:'
        = @room_booking.end_date.to_date

    .row
      .col-12
        %span= 'Host:'
        = poster.household_mention

    .row
      .col-12
        %span= 'Booked guest room:'
        = @room_booking.room.name

    - if @room_booking.description.present?
      .row
        .col-12
          %span= 'Notes:'
          = simple_format @room_booking.description

    .row.actions
      .col-12.col-md-6
        = link_to "Back to the guest room calendar", bookings_guests_path, class: 'btn btn-primary btn-md'